import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import Footer from "@/components/Footer";
import { Providers } from "./provider/nextThemeProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    // <html
    //   lang="en"
    //   className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    //   suppressHydrationWarning
    //   theme="dark"
    // >
    //   <body className="min-h-full flex flex-col bg-background text-foreground">
    //     <Providers>
    //       <Navbar />
    //       <main>{children}</main>
    //       {/* <Footer /> */}
    //     </Providers>
    //   </body>
    // </html>

    <html lang="en" className="scroll-smooth">
      <body className="bg-[#050505] text-[#e5e7eb] antialiased">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
